# Generated by Django 4.0.4 on 2022-05-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=20)),
                ('price', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.cart')),
                ('subTotal', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('shippingCharge', models.CharField(default='100', max_length=100)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('price', models.CharField(default='0', max_length=100)),
                ('stockCount', models.IntegerField(default='0')),
                ('category', models.ForeignKey(default='dfd', on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('subCategory', models.ForeignKey(default='ffsf', on_delete=django.db.models.deletion.DO_NOTHING, to='api.subcategory')),
            ],
        ),
    ]
